### ISSUE TITLE
Manipulate spoilers

### ISSUE THREAD

**Issue by jenstornell** [molocLab/kirby-calendar-board#16]
I think it's good to have this as an own issue.

I've seen your feature preview (image below). 

Now it might work something like this:

```
calendar:
  label: Calendar
  type:  calendarboard
  spoilers: info1,info2
```

What worries me is that if I have a select field with the labels "Cottage 1" and "Cottage 2", then the values for them might be "1" and "2".

Then the spoilers would show just the numbers and it's hard to figure out what they mean.

In my previous comment I had a suggestion of making it like an array with key and value, but now when I think about it, there would be better to have a snippet for it where the result is returned.

**This is an example of a snippet:**
```
if( $cottage_selector === 1 ) {
    echo 'Cottage: Red';
} else {
    echo 'Cottage: ' . $cottage_selector;
}
```

That means the echo will be returned by the snippet, so you can parse the content to make an nice formating.

**You image**

![image](https://cloud.githubusercontent.com/assets/927011/12810027/c71432da-cb23-11e5-841a-17a5bb0c6b4e.png)

**Comment by molocLab** [comment]
I decided to develop spoiler feature in the same way of "entry template" of structure field.

```
calendar:
  label: Calendar
  type:  calendarboard
  spoiler: Some text {{info1}}, other text {{info2}}
```

So, double curly brackets define a variable and will be replaced with the appropriate content in calendar board interface.
