### ISSUE TITLE
Classifying events by colors

### ISSUE THREAD

**Issue by molocLab** [molocLab/kirby-calendar-board#19]
![download_color](https://cloud.githubusercontent.com/assets/11831276/12919932/a4413ad8-cf46-11e5-9d65-dfdb03a84a63.png)

**Comment by jenstornell** [comment]
Really nice! I hope it's possible to have any color, not a predefined set.

**Comment by molocLab** [comment]
Yes, of course.
You can manage them through a select field in day blueprint:

```
      category:
        label: Category
        type: select
        options:
          11644D: Category 1
          A0B046: Category 2
          F2C94E: Category 3
          F78145: Category 4
          F24E4E: Category 5
```

(Not very satisfied with this solution)

**Comment by jenstornell** [comment]
I think you have it the wrong way.

```
options:
  category1: '#232322'
  category2: 'rgba(0,0,0,.5)'
```

This feels more natural. A key / value approach.

**Comment by molocLab** [comment]
In that way the editor will see:
![download_pattern](https://cloud.githubusercontent.com/assets/11831276/12920938/24dfbe18-cf4b-11e5-9dbc-0fa36a395c63.png)

Not very natural :)

**Comment by jenstornell** [comment]
What I don't like the most about your version is that a key is the color. Maybe later the user want to change the color. If that is done, every calendar task will lose the color that has that color.

I mean change:

```
11644D
```

to

```
000000
```

Will make the select key change and that means nothing is longer saved on that key because the key would now be 00000 but the saved value will still be 11644D.

**Comment by molocLab** [comment]
You are right, but I can't ask to a user to choose between a bunch of hexs.
Maybe, the best solution is to use a blueprint like:

```
options:
  category1: Category one
  category2: Category two
  category3: Category three
  ....
```

And then, somewhere in the plugin, use a reference array category -> color.
